/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    "api interval": {                                 "en": "API interval (in seconds)",                        "de": "API-Intervall (in Sekunden)",                      "ru": "Интервал API (в секундах)",                        "pt": "Intervalo de API (em segundos)",                   "nl": "API-interval (in seconden)",                       "fr": "Intervalle API (en secondes)",                     "it": "Intervallo API (in secondi)",                      "es": "Intervalo API (en segundos)",                      "pl": "Interwał API (w sekundach)",                       "uk": "Інтервал API (у секундах)",                        "zh-cn": "API 间隔（以秒为单位）"},
    "api key": {                                      "en": "API-Key",                                          "de": "API-Schlüssel",                                    "ru": "API-ключ",                                         "pt": "Chave API",                                        "nl": "API sleutel",                                      "fr": "Clé API",                                          "it": "Chiave API",                                       "es": "Clave API",                                        "pl": "Klucz API",                                        "uk": "API-ключ",                                         "zh-cn": "API密钥"},
    "how to get token": {                             "en": "How to get a token",                               "de": "So erhalten Sie ein Token",                        "ru": "Как получить токен",                               "pt": "Como obter token",                                 "nl": "Hoe een token te verkrijgen",                      "fr": "Comment obtenir un jeton",                         "it": "Come ottenere il gettone",                         "es": "Como conseguir ficha",                             "pl": "Jak zdobyć token",                                 "uk": "Як отримати токен",                                "zh-cn": "如何获取代币"},
};